<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-ABRF4IV4" failures="1" tests="1" name="TestNgLearning.Testcase2" time="0.009" errors="0" timestamp="2021-05-02T21:16:17 IST" skipped="0">
  <testcase classname="TestNgLearning.Testcase2" name="assertTest" time="0.009">
    <failure message="The following asserts failed:
	Titles not matching up expected [Gmail.com] but found [yahoo.com],
	Testcase returning false expected [true] but found [false],
	intentionally failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Titles not matching up expected [Gmail.com] but found [yahoo.com],
Testcase returning false expected [true] but found [false],
intentionally failed
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestNgLearning.Testcase2.assertTest(Testcase2.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- assertTest -->
  <system-out>
Testcase Failed - Capturing SS as well <a href ="C:\Users\HP\IdeaProjects\Selenium\Screenshot\Tue_Apr_27_17_09_29_IST_2021.jpg" target = "_blank">Screenshot Link</a> <br> <a href ="C:\Users\HP\IdeaProjects\Selenium\Screenshot\Tue_Apr_27_17_09_29_IST_2021.jpg" target = "_blank"><img src ="C:\Users\HP\IdeaProjects\Selenium\Screenshot\Tue_Apr_27_17_09_29_IST_2021.jpg" height = 200 width = 200 ></a>  </system-out>
</testsuite> <!-- TestNgLearning.Testcase2 -->
